class HeroVO {
	/** 英雄唯一ID */
	public heroId: number;
	/** 名字 */
	public name: string;
	/** 品质 */
	public quality: number;
	/** 子弹ID */
	public bulletId: number;
	/** 骨骼动画资源的名称 */
	public assetname: string;
	/** 子弹发射间隔 */
	public delay: number;
	/** 攻击距离 */
	public distance: number;
	/** 购买价格 */
	public gold: number;
	/** 出生音效 */
	public bornSound: string;
}